In [14]:
import numpy as np


import numpy as np

if __name__ == '__main__':
    i = 0
    np.random.seed()
  
    while(i<2):
        print(np.random.randn(1, 5))
        i += 1
    np.random.seed()
    print(np.random.randn(2, 5))
    np.random.seed()
    i = 0
    while(i < 2):
        print(np.random.randn(1, 5))
        i += 1



[[ 1.21874888 -0.34017498  2.29107481 -1.95019018  0.87988478]]
[[-1.46744399 -1.31540597 -0.55580222  1.0972647  -1.17334236]]
[[-0.5700958  -0.26315445 -0.10943155 -0.50284838  0.34938949]
 [-0.31567279 -0.05553784  0.65613749 -1.25110494 -0.01811317]]
[[-1.48242208 -0.09601068  0.37478367 -2.05843224  0.23230993]]
[[-1.07310385  0.27492506 -1.79955829  0.28253895  0.42070502]]


In [18]:
3/2

3.2/3
4/3

1.3333333333333333

In [28]:
print(r'dksmfls\\')
print(r"sf'nfs""\\")gb 
print(str('sfs'))
print(repr("sfsfsf"))

dksmfls\\
sf'nfs\
sfs
'sfsfsf'


In [47]:
sentence = 'please input a sentence :'
screen_width = 80
slen = len(sentence)

box_width = slen + 6
left_margin = (screen_width - box_width) // 2

print(' '*left_margin + '+' + '-'*(box_width-2) + '+')
print(' '*left_margin + '| ' + '  ' * slen + ' |')
print(' '*left_margin + '| ' + sentence + ' |')
print(' '*left_margin + '| ' + ' ' * slen + ' |')
print(' '*left_margin + '+' + '-'*(box_width-2) + '+')


                        +-----------------------------+
                        |                                                    |
                        | please input a sentence : |
                        |                           |
                        +-----------------------------+


StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.